services:
  streamlit:
    build:
      context: .
      dockerfile: docker/streamlit.Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    user: "${PRISM_UID:-1000}:${PRISM_GID:-1000}"
    ports:
      - "8501:8501"
    environment:
      STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
      STREAMLIT_SERVER_PORT: "8501"
    runtime: nvidia
